### ISSUE TITLE
All Products Page (React) - As a visitor, i want to view the full list of products so that I can see everything that's available.

### ISSUE THREAD

**Issue by BFriedman117** [1710-most-graceful-shoppers/grace-shopper#5]

**Comment by sarahzhao25** [comment]
Would you want to also include 'categories' and a 'search' option to filter for what you need? Similar to Juke search, so it's live. 'categories' may be dealt with its own model, perhaps. Unsure of how to connect or filter by category otherwise without needing to touch the database again.
